### ISSUE TITLE
MAJOR ISSUE : Please fix in pub.dev , repository content couldnt be retrieved

### ISSUE THREAD

**Issue by PistonShot1** [droibit/flutter_custom_tabs#171]
Problem : Couldnt retrieve the package contents
0/10 points: Provide a valid pubspec.yaml
Failed to verify repository URL.
Please provide a valid [repository](https://dart.dev/tools/pub/pubspec#repository) URL in pubspec.yaml, such that:

repository can be cloned,
a clone of the repository contains a pubspec.yaml, which:,
contains name: flutter_custom_tabs,
contains a version property, and,
does not contain a publish_to property.
Unable to access git repository: Could not accept branch na.....

I couldnt use it ,unless i specify the github url directly from this source, please fix

**Comment by droibit** [comment]
Thank you for the feedback.

The following warning on pub.dev has been resolved with the release of v2.0.0:

> Failed to verify repository URL.
