### ISSUE TITLE
Launcher.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by rignaneseleo** [droibit/flutter_custom_tabs#19]
Hello,
thanks for the good job.

When I try to build the apk with the version 0.6.0 I get the error
> Note: /Users/leonardorignanese/.pub-cache/hosted/pub.dartlang.org/flutter_custom_tabs-0.6.0/android/src/main/java/com/github/droibit/flutter/plugins/customtabs/internal/Launcher.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details. 

Why? How can I fix it?

**Comment by droibit** [comment]
Thank you for your patience.

The warnings has been fixed in the stable release of `flutter_custom_tabs` v2.0.

Please let me know if you have any other questions or feedback.
