### ISSUE TITLE
Get notified when custom_tabs is closed

### ISSUE THREAD

**Issue by TheMisir** [droibit/flutter_custom_tabs#23]
I need to detect and do something when custom_tabs were closed.

For example, I need to open the payment window. After payment is being made the window will be closed and I want to check payment status and navigate the user to a successful/failed screen.

For now, this method ("on closed" callback) is not provided by `flutter_custom_tabs`, due that I need to move to `flutter_inappwebview` but this package is simpler than that one. So I might come back if that functionality is added.

**Comment by tiramisuuuu** [comment]
@TheMisir 
I have a workaround for that. It worked for me, so maybe it works for you as well:
Add your State to WidgetsBindingObserver and override this Future.
`
class _SomethingState extends State<Something> with WidgetsBindingObserver {
@override
  Future<Null> didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.inactive:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
        //do something when the user leaves your app
        break;
      case AppLifecycleState.resumed:
        //do something when the user resumes your app (e.g. by closing the custom tab)
        break;
    }
  }`
}

I hope it works!

**Comment by TheMisir** [comment]
Thanks :)
