### ISSUE TITLE
Tab Not Opening in Release Mode I am getting black screen.

### ISSUE THREAD

**Issue by pktintali** [droibit/flutter_custom_tabs#24]
My Tabs are working fine in debug mode but in release mode tabs are not opening.I am getting only black screen.

**this is my flutter doctor output**
C:\Users\user\AndroidStudioProjects\Flutter Projects\hind_news>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter\flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • SM G610F • 33006936147764cd • android-arm • Android 8.1.0 (API 27)

• No issues found!

**and my pubspec.yaml is.......**

name: hind_news
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  webview_flutter: ^0.3.19+5
  flutter_custom_tabs: ^0.6.0
  shared_preferences: ^0.5.6
  dynamic_theme: ^1.0.0
  cached_network_image: ^2.0.0
  #pull_to_refresh: ^1.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
   - images/
  fonts:
    - family: Gelasio
      fonts:
        - asset: fonts/Gelasio-Medium.ttf

**I am using this method for launching tabs..**

  static void launchURL(BuildContext context, String url) async {
    try {
      await launch(
        url,
        option: CustomTabsOption(
          toolbarColor: Theme.of(context).primaryColor,
          enableDefaultShare: true,
          enableUrlBarHiding: true,
          showPageTitle: true,
          animation: CustomTabsAnimation.slideIn(),
          extraCustomTabs: <String>[
            // ref. https://play.google.com/store/apps/details?id=org.mozilla.firefox
            'org.mozilla.firefox',
            // ref. https://play.google.com/store/apps/details?id=com.microsoft.emmx
            'com.microsoft.emmx',
          ],
        ),
      );
    } catch (e) {
      debugPrint(e.toString());
    }
  }

**Comment by nws-jstorm** [comment]
I think this is related to #21 
Did you try removing the animation parameter in the CustomTabsOption constructor?

**Comment by pktintali** [comment]
> I think this is related to #21
> Did you try removing the animation parameter in the CustomTabsOption constructor?

Thanks! Problem Solved.
