### ISSUE TITLE
shows black screen while launching in release mode

### ISSUE THREAD

**Issue by Bidhanrai** [droibit/flutter_custom_tabs#25]

**Comment by h4rdw1r3** [comment]
Same issue. Could not open links in release mode. Has anyone found the fix or any workaround?

**Comment by Ionys320** [comment]
Same thing for me. But if press the return button of my phone, the custom tab appears…

**Comment by estevez-dev** [comment]
Look at #21, there is a solution

**Comment by Bidhanrai** [comment]
> Same thing for me. But if press the return button of my phone, the custom tab appears…

I could not find any work around that time. So I didn't used the plugin. Instead moved to native code to write platform specific code with platform channels

**Comment by haduyphuong** [comment]
Same here
