### ISSUE TITLE
Any way to change the color of the bar on iOS?

### ISSUE THREAD

**Issue by mdmota** [droibit/flutter_custom_tabs#29]
have any alternative or just for android?

**Comment by droibit** [comment]
The current latest version 0.7.0, does not support it.  

However, in a future release, we plan to remove `url_lancher` from the implementation for iOS   
and enable customization of navigation colors, etc.

**Comment by droibit** [comment]
The latest version supports customization of look & feel for iOS.
- https://pub.dev/packages/flutter_custom_tabs/versions/1.0.1
