### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

### ISSUE THREAD

**Issue by daniellampl** [droibit/flutter_custom_tabs#46]
## The Problem

When I try to open an url with `launch` I get the following error and the custom tab won't open:

E/MethodChannel#plugins.flutter.droibit.github.io/custom_tabs(14702): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
E/flutter (14702): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/flutter (14702): 	at com.github.droibit.flutter.plugins.customtabs.CustomTabsFactory.createIntent(CustomTabsFactory.java:56)
E/flutter (14702): 	at com.github.droibit.flutter.plugins.customtabs.CustomTabsPlugin.launch(CustomTabsPlugin.java:92)
E/flutter (14702): 	at com.github.droibit.flutter.plugins.customtabs.CustomTabsPlugin.onMethodCall(CustomTabsPlugin.java:75)
E/flutter (14702): 	at #io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (14702): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (14702): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (14702): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (14702): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (14702): 	at android.os.Looper.loopOnce(Looper.java:161)
E/flutter (14702): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (14702): 	at android.app.ActivityThread.main(ActivityThread.java:7796)
E/flutter (14702): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14702): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (14702): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
E/flutter (14702): )

## Additional Information

The gradle version of my project is `3.5.4`. I mention this because in older versions the application is not able to build in release mode.

I call launch without any option parameter values.

## Flutter Doctor Output

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale de-AT)
    • Flutter version 2.2.2 at /Users/daniellampl/development/src/flutter
    • Framework revision d79295af24 (10 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/daniellampl/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Pixel 5 (mobile) • 0B021FDD4001RX • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 91.0.4472.106

• No issues found!

**Comment by droibit** [comment]
I have released v1.0.2!
- https://pub.dev/packages/flutter_custom_tabs/versions/1.0.2
