### ISSUE TITLE
app crush on ios

### ISSUE THREAD

**Issue by SidneyMachara** [droibit/flutter_custom_tabs#50]
```
  try {
    await launch(url);
  } catch (e) {}
```
if the String `url` has a space at the beginning, the app crushes on IOS, on android nothing happens.
- maybe trim() the string before use, incase human forgot to do so

**Comment by droibit** [comment]
@SidneyMachara   
Thanks for the report!

We'll fix it so that the app doesn't crash when opening a URL that contains whitespace.  
(The current implementation behaved somewhat strangely 😅 ).
