### ISSUE TITLE
Url with headers not working

### ISSUE THREAD

**Issue by reshamRudra** [droibit/flutter_custom_tabs#51]
I am trying to load PDF using web url that needs x-auth in headers. I am always getting authentication error using this package

**Comment by droibit** [comment]
@reshamRudra   
Hi, This package supports request headers **only on Android**,   
so if you don't specify that, please refer to the code below.

```dart
await launch(
    customTabsOption: CustomTabsOption(
        headers: {
            'key': 'value'
        },
    ),
);
```

Request headers cannot be supported on iOS  
because it uses `SFSfariViewController` internally.

**Comment by droibit** [comment]
Reopen this issue if necessary.

**Comment by itsmerafial141** [comment]
Headers do not work when using CustomTabsOptions.externalBrowser and CustomTabsBrowserConfiguration

[✓] Flutter (Channel stable, 3.19.4, on macOS 15.1.1 24B91 darwin-arm64, locale en-ID)
    • Flutter version 3.19.4 on channel stable at /Users/rafial/fvm/versions/3.19.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (8 months ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rafial/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

**Comment by droibit** [comment]
Due to security considerations, there are limitations on the request headers that can be passed to Custom Tabs:
- [Approved CORS Request Headers](https://fetch.spec.whatwg.org/#cors-safelisted-request-header):
  - Can be passed to Custom Tabs.
  - Examples include accept-language, content-language, etc.
- Non-Approved CORS Headers:
  - Cannot be passed.
  - These headers can only be passed if the app and website are associated via Digital Asset Links, which this plugin does not currently support.

For more details, please refer to the official documentation:
- [Add extra HTTP request headers - Chrome Developers](https://developer.chrome.com/docs/android/custom-tabs/howto-custom-tab-request-headers)
