### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac' at custom tab plugin 

### ISSUE THREAD

**Issue by ayechan-maung** [droibit/flutter_custom_tabs#59]
android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:29: error: package com.github.droibit.flutter.plugins.customtabs does not exist
    flutterEngine.getPlugins().add(new com.github.droibit.flutter.plugins.customtabs.CustomTabsPlugin());
                                                                                    ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by SputNikPlop** [comment]
This has been fixed in the updated version of the plugin I believe.

**Comment by droibit** [comment]
Thank you for reporting this issue. It appears that the problem has been resolved in recent updates. 

I'm closing this issue now, but please feel free to reopen it or create a new one if you encounter this problem again.
