### ISSUE TITLE
Does it need <queries> element in AndroidManifest for API30?

### ISSUE THREAD

**Issue by afung2468** [droibit/flutter_custom_tabs#60]
For url_launcher, a <queries> element must be present in AndroidManifest for API30. Does this package require a <queries> element like url_launcher for API30?

**Comment by droibit** [comment]
No, you do not need to add the `queries` element explicitly to your project's AndroidManifest.  
It is automatically provided by the [CustomTabsLauncher](https://github.com/droibit/CustomTabsLauncher) library that this package depends on.
