### ISSUE TITLE
CustomTabsFactory.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by LightkingB** [droibit/flutter_custom_tabs#65]
Note: /home/beknazarov/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_custom_tabs-1.0.4/android/src/main/java/com/github/droibit/flutter/plugins/customtabs/CustomTabsFactory.java uses or overrides a deprecated API.

**Comment by graux** [comment]
Hi there! 
This issue is open more than 6 months now, is there any plan to fix it?
Thank you!

**Comment by luckyhandler** [comment]
Having the same issue with version `1.1.0` and `1.1.1`

**Comment by droibit** [comment]
Thank you for your patience.

The warnings has been fixed in the stable release of `flutter_custom_tabs` v2.0, which was released today.

Please let me know if you have any other questions or feedback.
