### ISSUE TITLE
Package needs updating

### ISSUE THREAD

**Issue by l-k22** [droibit/flutter_custom_tabs#7]
flutter_custom_tabs 0.4.0 depends on url_launcher 0.3.0, because _APP_NAME_ depends on url_launcher 4.0.1 version solving failed.

**Comment by melgu** [comment]
I have the same problem, but with flutter_custom_tabs 0.6.0 and url_launcher 6.0.3

**Comment by yogesh-xseed** [comment]
please update the package.

**Comment by gowtham-xseed** [comment]
+1

**Comment by SputNikPlop** [comment]
@droibit This issue is no longer relevant

**Comment by droibit** [comment]
Thanks for the heads up!

Since the issue appears to be resolved, I'll go ahead and close it.
