### ISSUE TITLE
How to close the in-app browser programmatically

### ISSUE THREAD

**Issue by fathah** [droibit/flutter_custom_tabs#70]
Hey, 
I have been using this package for a while.  I want to know (if it's already available\request a feature) how to close the in-app webview called using  `launch` function.

*Function*:
```java
  try {
    await launch(
      'URL_HERE',
      customTabsOption: const CustomTabsOption(
        toolbarColor: Color(0xff000000),
        enableDefaultShare: false,
        enableUrlBarHiding: true,
        showPageTitle: true,
        extraCustomTabs: <String>[
          'org.mozilla.firefox',
          'com.microsoft.emmx',
        ],
      ),
      safariVCOption: const SafariViewControllerOption(
        preferredBarTintColor: Color(0xff000000),
        preferredControlTintColor: Colors.white,
        barCollapsingEnabled: true,
        entersReaderIfAvailable: false,
        dismissButtonStyle: SafariViewControllerDismissButtonStyle.close,
      ),
    );
  } catch (e) {
    print(e.toString());
  }
```
![Screenshot 2022-11-21 101451](https://user-images.githubusercontent.com/48355244/202967689-1656eea4-8a0c-4111-ab6e-54cb329dd751.png)

I'hv marked it in the above image. The event called when the X button is clicked should be called programmatically.

**Comment by usman615** [comment]
How do I add desktop site option in tabbar

**Comment by champ96k** [comment]
Is there anyone have any updates?

**Comment by abdallah-odeh** [comment]
no updates? :(

**Comment by droibit** [comment]
A new method `closeAllIfPossible()` was added to the package to close custom tabs programmatically.
(There are no restrictions on iOS, but it works on Android 6.0 and above.)

To use it, please update the package to the latest v1.12.0.
